### PR TITLE
adding message with buttons

### PR DESCRIPTION
**Pull request by FelipeVeiga**
adding message with buttons

### CODE REVIEW

**Review by allburov — CHANGES_REQUESTED** [review]
Hi, great work, thank you! 

One thing - could you remove commented text? 
If the purpose of it to show how to use it - we should add a docstring to ApiOperation or an example

**Comment by FelipeVeiga** [comment]
> Hi, great work, thank you!
> 
> One thing - could you remove commented text? If the purpose of it to show how to use it - we should add a docstring to ApiOperation or an example

yes, you can remove the comments.
I dont know review the PR. 
Please, go ahead. thanks

**Review by FelipeVeiga — COMMENTED** [review]
remove comments

**Review by FelipeVeiga — COMMENTED** [review]
removing comments

**Comment by allburov** [comment]
@FelipeVeiga thank you!

**Pull request merged**
